### ISSUE TITLE
Questions about the training details or parameters to achieve the good results as reported in the paper

### ISSUE THREAD

**Issue by fyting131214** [katehai/m-cedm#1]
Hello,

If possible and convenient, could you please offer more information about the training details or parameters? For experiments with different equations, do I only need to modify the datasets? It seems that by following the prompts in this repository except the max_epochs (python run.py --config-name=config_adm_edm_mcedm_res32.yaml system=swe_per subname=swe_per dataroot=data datamodule.batch_size=16 diff_sampler.n_samples=1) , the results are not ideal but I don't know how to modify them and I haven't found a solition.  Any help or advice you could provide would be greatly appreciated. 

Thank you for your time and help!

**Comment by katehai** [comment]
Hi!

Thank you for the question!

I believe the parameters saved in the .yaml files should be correct. One thing to check is the number of samples (diff_sampler.n_samples variable). As mentioned in the paper, we report the results with 100 samples. I put diff_sampler.n_samples = 1 in the example just for faster calculation. It can be tried with a saved checkpoint using "eval_model.py".  Also, I believe that I used trainer.max_epochs=15000 for the experiments in Tables 1 and 2.

**Comment by fyting131214** [comment]
Hi,

Happy to receive your reply, and thank you for your advice and help.

I'll try it again with the following commands, and I was wondering if I’m right.

```python
python run.py --config-name=config_adm_edm_mcedm_res32.yaml system=swe_per subname=swe_per dataroot=data datamodule.batch_size=16 trainer.max_epochs=15000 diff_sampler.n_samples=100
``` 
```python
python eval_model.py --config-name=config_adm_edm_mcedm_res32.yaml system=swe_per subname=swe_per dataroot=data ckpt_path=logs/runs/run_name datamodule.batch_size=16 trainer.max_epochs=1 diff_sampler.n_samples=100
``` 

If you get a chance, could you please explain something that has confused me during my recent experiments? In my previous experiments, I used early stopping with monitor= "val_mae_loss" and patience=35. Here, I set val_mae_loss=val_mae_h+val_mae_loss_u. The best model ckpt is epoch_220.ckpt. The number 220 is significantly smaller than 15000. I'm a bit puzzled whether setting max_epochs=15000 would lead to overfitting, as callbacks_ddim.yaml saves the checkpoint at the maximum epoch. 

Additionally, if I perform an experiment on darcy,  do I only need to modify the 'system' and 'subname' like this?
```python
python run.py --config-name=config_adm_edm_mcedm_res32.yaml system=darcy subname=darcy dataroot=data datamodule.batch_size=16 trainer.max_epochs=15000 diff_sampler.n_samples=100
``` 
```python
python eval_model.py --config-name=config_adm_edm_mcedm_res32.yaml system=darcy subname=darcy  dataroot=data ckpt_path=logs/runs/run_name datamodule.batch_size=16 trainer.max_epochs=1 diff_sampler.n_samples=100
``` 
Thank you!

**Comment by fyting131214** [comment]
Hi,

Thanks to your generous advice and assistance in your busy schedule, the latest experimental results are much better than my previous ones! If it wasn't for your help, I might have been unable to find a solution.

Thank you again and wish you all the best!

**Comment by katehai** [comment]
Hi!

Happy to hear that the latest results are much better! 
Yes, in order to run the experiments with Darcy flow system, one needs just to change 'system' and 'subname' as you pointed out.
